apiVersion: v1
kind: Service
metadata:
  name: {{ include "hypertrophy-chart.fullname" . }}
  labels:
    {{- include "hypertrophy-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8000  # Burayı elle 8000 yapalım ki şüphe kalmasın
      protocol: TCP
      name: http
  selector:
    {{- include "hypertrophy-chart.selectorLabels" . | nindent 4 }}
