apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hypertrophy-engine-monitor
  namespace: monitoring
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hypertrophy-chart
  namespaceSelector:
    matchNames:
      - olympos-platform
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
